### PR TITLE
Disable astrowidgets pixel marking when WCS linked (PR to PR 14 to PR 2179)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address adding markers in pixel space breaking when there is rotation layer. Markers added with SkyCoord already satisfies "marks should adjust to a change in orientation layer" (see screenshots below).

This is a PR to:

* bmorris3/jdaviz#14

that is a PR to:

* spacetelescope/jdaviz#2179

I fixed the one test failure I know is caused by my change here. When I ran the full test suite locally, there were several other test failures that look like they are from different parts of the code, but the PR 2179 branch is also outdated compared to latest `main`, so some of those maybe already fixed in `main`, so the PR 2179 branch should be rebased first before fixing the tests.

### N-up E-left

[🐱](https://jira.stsci.edu/browse/JDAT-3945)

### CODE REVIEW

**Comment by kecnry** [comment]
does this address whether a given entry should or should not be in the data menu (or removed when changing from pixel->WCS linking)?  Or is the plan to put that directly in https://github.com/bmorris3/jdaviz/pull/14 and rebase this on top of that once that is merged?

**Comment by pllim** [comment]
> does this address whether a given entry should or should not be in the data menu (or removed when changing from pixel->WCS linking)? 

Data menu is irrelevant here. If it is now allowed, it won't be loaded in the first place. Once loaded, changing the linking type is disabled until all markers are removed. The latter is an existing behavior and if we end up moving to using a list of regions, also irrelevant.

**Comment by kecnry** [comment]
So is https://github.com/bmorris3/jdaviz/pull/14#discussion_r1380718246 no longer a concern?  If you add another viewer is the "+" button enabled/disabled as you'd expect?

**Comment by pllim** [comment]
> no longer a concern?

I can't keep track of what happened but Imviz now let me load the tables. Did you change the logic or something?

**Comment by pllim** [comment]
@kecnry , I see that you force pushed and now my diff also has your other changes. Is this intentional?

**Comment by kecnry** [comment]
I thought the discussed plan was to get https://github.com/bmorris3/jdaviz/pull/14 in and then re-open your branch on top of that (instead of PR to PR to PR)

**Comment by pllim** [comment]
Yeah... I didn't think that plan include force pushing to my branch so soon. I thought I would just rebase on top of Brett's branch after your PR is merged, which has not happened yet.

**Comment by kecnry** [comment]
I did not force push to your branch, just the base branch (`wcs-only-data-menu-fixes`)

**Comment by pllim** [comment]
Gonna close this and open against Brett's branch.

**Comment by pllim** [comment]
This is now https://github.com/bmorris3/jdaviz/pull/16

**Pull request closed without merging**
